import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/loader.css";
import "@/styles/admin.css";
import Navbar from "@/components/main/navbar";
import Footer from "@/components/footer";
import { AuthProvider } from "@/context/AuthContext";
import AuthGate from "@/components/auth/AuthGate";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="vi">
      <body>
        <AuthProvider>
          <AuthGate>
            <Navbar/>
            <div className="pb-20"></div>
            {children}
            <Footer/>
          </AuthGate>
        </AuthProvider>
      </body>
    </html>
  );
}

