export const BODY_MODELS = {
  avatar_female: '/model/body/male.glb',
  avatar_male:   '/model/body/male.glb',
} as const

export const GARMENTS = {
  hat: {
    cap_01: '/model/garments/hat/hat_cap_01.glb',
    beanie_01: '/model/garments/hat/hat_beanie_01.glb',
  },
  top: {
    tshirt_01: '/model/cloth/shirt/red_shirt.glb',
    hoodie_01: '/model/cloth/shirt/aodep.glb',
    sweater_01: '/model/cloth/shirt/shirt_sweater_01.glb',
    hoodie_02: '/model/cloth/shirt/shirt_hoodie_02.glb',
    hoodie_03: '/model/cloth/shirt/shirt_hoodie_03.glb',
    hoodie_04: '/model/cloth/shirt/shirt_hoodie_04.glb',
    hoodie_05: '/model/cloth/shirt/shirt_hoodie_05.glb',    
    hoodie_06: '/model/cloth/shirt/shirt_hoodie_06.glb',    
    hoodie_07: '/model/cloth/shirt/shirt_hoodie_07.glb',    
    hoodie_08: '/model/cloth/shirt/shirt_hoodie_08.glb',    
    hoodie_09: '/model/cloth/shirt/shirt_hoodie_09.glb',    
    hoodie_10: '/model/cloth/shirt/shirt_hoodie_10.glb',    
    hoodie_11: '/model/cloth/shirt/shirt_hoodie_11.glb',    
    hoodie_12: '/model/cloth/shirt/shirt_hoodie_12.glb',    
    hoodie_13: '/model/cloth/shirt/shirt_hoodie_13.glb',    
    hoodie_14: '/model/cloth/shirt/shirt_hoodie_14.glb',    
    hoodie_15: '/model/cloth/shirt/shirt_hoodie_15.glb',    
    hoodie_16: '/model/cloth/shirt/shirt_hoodie_16.glb',    
    hoodie_17: '/model/cloth/shirt/shirt_hoodie_17.glb',    
    hoodie_18: '/model/cloth/shirt/shirt_hoodie_18.glb',    
    hoodie_19: '/model/cloth/shirt/shirt_hoodie_19.glb',    
    hoodie_20: '/model/cloth/shirt/shirt_hoodie_20.glb',    
    hoodie_21: '/model/cloth/shirt/shirt_hoodie_21.glb',    
    hoodie_22: '/model/cloth/shirt/shirt_hoodie_22.glb',    
    hoodie_23: '/model/cloth/shirt/shirt_hoodie_23.glb',    
    hoodie_24: '/model/cloth/shirt/shirt_hoodie_24.glb',    
    hoodie_25: '/model/cloth/shirt/shirt_hoodie_25.glb',    
    hoodie_26: '/model/cloth/shirt/shirt_hoodie_26.glb',    
    hoodie_27: '/model/cloth/shirt/shirt_hoodie_27.glb',    
    hoodie_28: '/model/cloth/shirt/shirt_hoodie_28.glb',    
    hoodie_29: '/model/cloth/shirt/shirt_hoodie_29.glb',    
    hoodie_30: '/model/cloth/shirt/shirt_hoodie_30.glb',    
    hoodie_31: '/model/cloth/shirt/shirt_hoodie_31.glb',    
    hoodie_32: '/model/cloth/shirt/shirt_hoodie_32.glb',    
    hoodie_33: '/model/cloth/shirt/shirt_hoodie_33.glb',    
    hoodie_34: '/model/cloth/shirt/shirt_hoodie_34.glb',    
    hoodie_35: '/model/cloth/shirt/shirt_hoodie_35.glb',    
    hoodie_36: '/model/cloth/shirt/shirt_hoodie_36.glb',    
    hoodie_37: '/model/cloth/shirt/shirt_hoodie_37.glb',    
    hoodie_38: '/model/cloth/shirt/shirt_hoodie_38.glb',    
    hoodie_39: '/model/cloth/shirt/shirt_hoodie_39.glb',    
    hoodie_40: '/model/cloth/shirt/shirt_hoodie_40.glb',    
    hoodie_41: '/model/cloth/shirt/shirt_hoodie_41.glb',    
    hoodie_42: '/model/cloth/shirt/shirt_hoodie_42.glb',    
    hoodie_43: '/model/cloth/shirt/shirt_hoodie_43.glb',    
    hoodie_44: '/model/cloth/shirt/shirt_hoodie_44.glb',    
    hoodie_45: '/model/cloth/shirt/shirt_hoodie_45.glb',     
  },
  bottom: {
    cap_01: '/model/cloth/pants/pants.glb',
    beanie_01: '/model/cloth/pants/shorts.glb',
  },
  shoes: {
    pants: '/model/garments/shoes/shoes_sneaker_01.glb',
    boot_01:    '/model/garments/shoes/shoes_boot_01.glb',
    
  }
} as const